CREATE TABLE Client (
    ID INT NOT NULL AUTO_INCREMENT,
    NameClient TEXT NOT NULL,
    Adress VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE Phone (
    PhoneNum VARCHAR(15) NOT NULL,
    ClientID INT,
    PhoneID INT AUTO_INCREMENT,
    CurrDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PhoneID),
    FOREIGN KEY (ClientID) REFERENCES Client(ID) ON DELETE SET NULL
);

